import { describe, it, expect } from "vitest";
import { emitProfileYaml } from "../../src/analyzer/profile-scaffold/emit.js";
import { parseProfile } from "../../src/parser/profile-parser.js";
import type { DSProfile } from "../../src/types/profile.js";

function minimalProfile(over: Partial<DSProfile> = {}): DSProfile {
  return {
    name: "Acme",
    version: "1.0.0",
    cdf_version: ">=1.0.0",
    dtcg_version: "2025.10",
    description: "Acme design system.",
    vocabularies: {},
    token_grammar: {},
    token_layers: [],
    interaction_patterns: {},
    theming: { modifiers: {}, set_mapping: {} },
    naming: {
      css_prefix: "ac-",
      token_prefix: "--ac-",
      methodology: "BEM",
      pattern: "{prefix}{component}",
      casing: { component_names: "PascalCase", properties: "camelCase" },
      reserved_names: {},
    },
    categories: {},
    ...over,
  };
}

describe("emitProfileYaml", () => {
  it("emits valid YAML that round-trips through parseProfile", () => {
    const profile = minimalProfile({
      vocabularies: {
        hierarchy: {
          description: "emphasis",
          values: ["primary", "secondary"],
        },
      },
    });
    const yaml = emitProfileYaml(profile, { date: "2026-04-18" });
    const parsed = parseProfile(yaml);
    expect(parsed.name).toBe("Acme");
    expect(parsed.vocabularies.hierarchy.values).toEqual(["primary", "secondary"]);
  });

  it("includes a top-of-file provenance comment with date and non-overwrite note", () => {
    const yaml = emitProfileYaml(minimalProfile(), { date: "2026-04-18" });
    expect(yaml).toMatch(/# Auto-generated by cdf_profile_scaffold/i);
    expect(yaml).toMatch(/2026-04-18/);
    expect(yaml).toMatch(/edit this file by hand/i);
  });

  it("includes source description when provided", () => {
    const yaml = emitProfileYaml(minimalProfile(), {
      date: "2026-04-18",
      sourceDescription: "scaffold-input.json (figma)",
    });
    expect(yaml).toContain("scaffold-input.json (figma)");
  });

  it("renders per-section comment headers above top-level keys", () => {
    const profile = minimalProfile({
      vocabularies: {
        hierarchy: { description: "emphasis", values: ["primary"] },
      },
    });
    const yaml = emitProfileYaml(profile, { date: "2026-04-18" });
    // Vocabularies section has its own comment header
    expect(yaml).toMatch(/# Vocabularies/i);
    expect(yaml).toMatch(/# Token Grammar/i);
    expect(yaml).toMatch(/# Theming/i);
    expect(yaml).toMatch(/# Naming/i);
  });

  it("surfaces per-section summary notes when provided", () => {
    const profile = minimalProfile({
      vocabularies: {
        hierarchy: { description: "e", values: ["primary"] },
      },
    });
    const yaml = emitProfileYaml(profile, {
      date: "2026-04-18",
      summary: {
        vocabularies: "1 vocabulary inferred from 1 component property.",
        token_grammar: "No grammars inferred — all tokens emitted as standalone_tokens.",
      },
    });
    expect(yaml).toContain("1 vocabulary inferred from 1 component property.");
    expect(yaml).toContain("No grammars inferred");
  });

  it("emits YAML parseable by yaml.parse without errors", () => {
    const profile = minimalProfile({
      vocabularies: {
        hierarchy: {
          description: "Visual emphasis level.",
          values: ["primary", "secondary", "tertiary"],
        },
        size: {
          description: "Scale axis.",
          values: ["sm", "md", "lg"],
        },
      },
      token_grammar: {
        controls: {
          pattern: "color.controls.{hierarchy}.{element}.{state}",
          dtcg_type: "color",
          description: "Interactive controls.",
        },
      },
      theming: {
        modifiers: {
          semantic: {
            description: "Light/Dark",
            contexts: ["Light", "Dark"],
          },
        },
        set_mapping: {},
      },
    });
    const yaml = emitProfileYaml(profile, { date: "2026-04-18" });
    expect(() => parseProfile(yaml)).not.toThrow();
  });

  it("preserves multi-line descriptions as block scalars (readable in YAML)", () => {
    const profile = minimalProfile({
      vocabularies: {
        hierarchy: {
          description: "Line one.\nLine two.\nLine three.",
          values: ["a"],
        },
      },
    });
    const yaml = emitProfileYaml(profile, { date: "2026-04-18" });
    const parsed = parseProfile(yaml);
    expect(parsed.vocabularies.hierarchy.description).toContain("Line one.");
    expect(parsed.vocabularies.hierarchy.description).toContain("Line three.");
  });

  it("emits identity keys (name, version, cdf_version, dtcg_version) first", () => {
    const yaml = emitProfileYaml(minimalProfile(), { date: "2026-04-18" });
    const identityRegion = yaml.split(/# Vocabularies/i)[0];
    expect(identityRegion).toMatch(/name:\s*Acme/);
    expect(identityRegion).toMatch(/version:\s*"?1\.0\.0"?/);
    expect(identityRegion).toMatch(/cdf_version:/);
    expect(identityRegion).toMatch(/dtcg_version:/);
  });

  it("lists decisions under a decision log header when decisions are provided", () => {
    const yaml = emitProfileYaml(minimalProfile(), {
      date: "2026-04-18",
      decisions: [
        {
          milestone_id: "vocab-naming",
          source: "user",
          summary: "`hierarchy` split from `variant` (user-accepted)",
        },
      ],
    });
    expect(yaml).toMatch(/# Decision log/i);
    expect(yaml).toMatch(/hierarchy.*variant/);
  });
});
