import type {
  FindingsOutput,
  CollisionFinding,
  OutlierFinding,
  BlindSpotFinding,
  CrossValidationFinding,  // NEW Plan 1.3.5
} from './types.js';
import { formatProseMarker, formatNameMarker, formatClassificationMarker } from './marker-grammar.js';
import { buildHint } from './hint-builder.js';

export function renderFindings(f: FindingsOutput): string {
  const lines: string[] = [];
  lines.push('# DRAFT — UNCLASSIFIED Findings');
  lines.push('');
  lines.push('> Generated by cdf-core/snapshot. Marker grammar:');
  lines.push('> TBD-prose hint="..." → write 1–2 sentences using the hint as context.');
  lines.push('> TBD-classification candidates="[a,b,c]" hint="..." → pick one, replace.');
  lines.push('> TBD-name candidates="[a,b]" hint="..." → pick one, replace.');
  lines.push('');
  lines.push('## Collisions');
  lines.push('');
  for (const [i, c] of f.collisions.entries()) renderCollision(lines, c, i + 1);
  lines.push('## Outliers');
  lines.push('');
  for (const [i, o] of f.outliers.entries()) renderOutlier(lines, o, f.collisions.length + i + 1);
  if (f.crossValidations && f.crossValidations.length > 0) {
    lines.push('## Cross-Validations');
    lines.push('');
    for (const cv of f.crossValidations) renderCrossValidation(lines, cv);
    lines.push('');
  }
  lines.push('## Blind Spots');
  lines.push('');
  for (const [i, b] of f.blindSpots.entries()) renderBlindSpot(lines, b, f.collisions.length + f.outliers.length + i + 1);
  return lines.join('\n');
}

function renderCollision(out: string[], c: CollisionFinding, idx: number): void {
  out.push(`### Finding ${idx}`);
  out.push('');
  out.push(`- **Type:** ${c.type}`);
  out.push(`- **Members:** [\`${c.members[0]}\`, \`${c.members[1]}\`]`);
  out.push(`- **Evidence:** ${c.evidence}`);
  out.push(`- **Plain language:** ${formatProseMarker(buildHint('Why are these two vocabularies colliding, and which name should win?', c.hintContext))}`);
  out.push(`- **Severity:** ${formatClassificationMarker(c.classificationCandidates, buildHint('How impactful is this collision?', c.hintContext))}`);
  if (c.suggestCanonical) {
    out.push(`- **Suggested canonical:** ${formatNameMarker([c.members[0], c.members[1]], buildHint('Which member should be canonical? Higher set_coverage usually wins.', c.hintContext))}`);
  }
  out.push('');
}

function renderOutlier(out: string[], o: OutlierFinding, idx: number): void {
  out.push(`### Finding ${idx}`);
  out.push('');
  out.push(`- **Type:** ${o.type}`);
  out.push(`- **Vocab:** ${o.vocab}`);
  out.push(`- **Set:** ${o.set}`);
  out.push(`- **Outlier value:** "${o.outlierValue}"`);
  out.push(`- **Evidence:** ${o.evidence}`);
  out.push(`- **Plain language:** ${formatProseMarker(buildHint(`Why does ${o.set} carry an extra value '${o.outlierValue}' that other components don't?`, o.hintContext))}`);
  out.push('');
}

function renderBlindSpot(out: string[], b: BlindSpotFinding, idx: number): void {
  out.push(`### Finding ${idx}`);
  out.push('');
  out.push(`- **Source:** ${b.source}`);
  out.push(`- **Evidence:** ${b.evidence}`);
  out.push(`- **Plain language:** ${formatProseMarker(buildHint('What is missing because of this source-restriction, and what can we still derive?', { setCoverage: b.hintContext.setCoverage ?? 0 }))}`);
  out.push('');
}

function renderCrossValidation(out: string[], cv: CrossValidationFinding): void {
  if (cv.kind === 'vocab-token-gap') {
    out.push(`- **vocab-token-gap** — '${cv.vocab}.${cv.missingValue}': ${cv.evidence}`);
  } else {
    out.push(`- **orphan-modifier-context** — '${cv.modifier}/${cv.orphanContext}': ${cv.evidence}`);
  }
}
