import type {
  SnapshotAnalyzerOutput,
  SnapshotVocabulary,
  SnapshotTokenLayer,
  SnapshotThemingModifier,
  SetMappingEntry,
} from './types.js';
import { formatProseMarker } from './marker-grammar.js';
import { buildHint } from './hint-builder.js';

export interface ProfileMeta {
  dsName: string;
  figmaFileKey: string;
  generatedAt: string;
  generatedBy: string;
}

export function renderProfile(output: SnapshotAnalyzerOutput, meta: ProfileMeta): string {
  const lines: string[] = [];
  lines.push('# Generated by cdf-core/snapshot — DO NOT hand-edit deterministic fields');
  lines.push('');
  lines.push('ds:');
  lines.push(`  name: ${meta.dsName}`);
  lines.push(`  figma_file_key: ${meta.figmaFileKey}`);
  lines.push(
    `  description: ${formatProseMarker(buildHint('Describe this DS in 1–2 sentences.', { setCoverage: output.vocabularies.length }))}`,
  );
  lines.push(`  generated_at: ${meta.generatedAt}`);
  lines.push(`  generated_by: ${meta.generatedBy}`);
  lines.push('');
  lines.push(...renderVocabularies(output.vocabularies));
  lines.push('');
  lines.push(...renderTokenLayers(output.tokenLayers));
  lines.push('');
  lines.push(...renderTheming(output.themingModifiers, output.setMapping));
  lines.push('');
  return lines.join('\n');
}

// MAP shape — matches Record<string, Vocabulary> in profile.ts:24
function renderVocabularies(vocabs: SnapshotVocabulary[]): string[] {
  const out: string[] = ['vocabularies:'];
  for (const v of vocabs) {
    out.push(`  ${v.name}:`);
    out.push(
      `    description: ${formatProseMarker(buildHint('What does this vocabulary express across components?', v.hintContext))}`,
    );
    out.push(`    values: [${v.values.join(', ')}]`);
    out.push(`    set_coverage: ${v.setCoverage}`);
    out.push(`    is_boolean_shape: ${v.isBooleanShape}`);
  }
  return out;
}

// ARRAY shape — matches TokenLayer[] in profile.ts:30
function renderTokenLayers(layers: SnapshotTokenLayer[]): string[] {
  const out: string[] = ['token_layers:'];
  for (const l of layers) {
    out.push(`  - name: ${l.name}`);
    out.push(
      `    description: ${formatProseMarker(buildHint('What does this layer carry in the cascade?', l.hintContext))}`,
    );
    out.push(`    sets: [${l.sets.join(', ')}]`);
  }
  return out;
}

// theming.modifiers MAP + theming.set_mapping populated from analyzer output (Plan 1.2)
function renderTheming(mods: SnapshotThemingModifier[], setMapping: Record<string, SetMappingEntry>): string[] {
  const out: string[] = ['theming:', '  modifiers:'];
  for (const m of mods) {
    out.push(`    ${m.name}:`);
    out.push(
      `      description: ${formatProseMarker(buildHint('What does this modifier control across the system?', m.hintContext))}`,
    );
    out.push(`      contexts: [${m.contexts.join(', ')}]`);
  }

  const setKeys = Object.keys(setMapping);
  if (setKeys.length === 0) {
    out.push('  set_mapping: {}');
  } else {
    out.push('  set_mapping:');
    for (const key of setKeys.sort()) {
      const entry = setMapping[key];
      out.push(`    ${quoteSetKey(key)}: ${formatSetMappingEntry(entry)}`);
    }
  }
  return out;
}

function quoteSetKey(key: string): string {
  return `"${key}"`;
}

function formatSetMappingEntry(entry: SetMappingEntry): string {
  if (entry.always_enabled === true) return '{always_enabled: true}';
  return `{modifier: ${entry.modifier}, context: ${entry.context}}`;
}
