/**
 * Profile YAML emission — serialises a DSProfile to comment-annotated
 * YAML suitable for hand-editing.
 *
 * Section-by-section assembly (same pattern as the Component scaffold
 * in src/scaffold/generate.ts) gives precise control over comment
 * placement without wrestling the yaml Document API. Each section is
 * `stringify`-ed independently and joined with header comments.
 *
 * Design §3.7.
 */

import { stringify } from "yaml";
import type { DSProfile } from "../../types/profile.js";

export interface EmitDecision {
  milestone_id: string;
  source: string;
  summary: string;
}

export interface EmitMetadata {
  date: string;
  sourceDescription?: string;
  /** Optional per-section summary lines inserted above each section header. */
  summary?: Record<string, string>;
  /** Decisions made during scaffolding — surfaced in a decision-log block. */
  decisions?: EmitDecision[];
}

interface Section {
  key: keyof DSProfile;
  comment: string;
  required: boolean;
}

const SECTIONS: Section[] = [
  { key: "vocabularies", comment: "# Vocabularies", required: true },
  { key: "token_grammar", comment: "# Token Grammar", required: true },
  { key: "token_layers", comment: "# Token Layers", required: false },
  { key: "standalone_tokens", comment: "# Standalone Tokens", required: false },
  { key: "interaction_patterns", comment: "# Interaction Patterns", required: false },
  { key: "theming", comment: "# Theming", required: true },
  { key: "accessibility_defaults", comment: "# Accessibility Defaults", required: false },
  { key: "naming", comment: "# Naming", required: true },
  { key: "categories", comment: "# Categories", required: false },
  { key: "assets", comment: "# Assets", required: false },
  { key: "css_defaults", comment: "# CSS Defaults", required: false },
];

export function emitProfileYaml(profile: DSProfile, metadata: EmitMetadata): string {
  const parts: string[] = [buildProvenanceBlock(metadata)];

  if (metadata.decisions && metadata.decisions.length > 0) {
    parts.push(buildDecisionLogBlock(metadata.decisions));
  }

  parts.push("", buildIdentityBlock(profile));

  for (const section of SECTIONS) {
    const value = profile[section.key];
    if (value === undefined || value === null) {
      if (!section.required) continue;
      // Required-but-empty section: emit `{}` with header so the output stays valid
      parts.push("", section.comment, "", `${section.key}: {}`);
      continue;
    }
    if (isEmpty(value) && !section.required) continue;

    parts.push("", section.comment);
    const summaryNote = metadata.summary?.[section.key as string];
    if (summaryNote) parts.push(`# ${summaryNote}`);
    parts.push("", stringifySection(section.key as string, value).trimEnd());
  }

  return parts.join("\n") + "\n";
}

// ─── Blocks ─────────────────────────────────────────────────────────────────

function buildProvenanceBlock(meta: EmitMetadata): string {
  const lines = [
    `# Auto-generated by cdf_profile_scaffold on ${meta.date}` +
      (meta.sourceDescription ? ` from ${meta.sourceDescription}.` : "."),
    "# You may edit this file by hand — future scaffold invocations error",
    "# if the file already exists (use a different output_path to write elsewhere).",
  ];
  return lines.join("\n");
}

function buildDecisionLogBlock(decisions: EmitDecision[]): string {
  const lines = ["", "# Decision log:"];
  for (const d of decisions) {
    lines.push(`#   - [${d.milestone_id} · source:${d.source}] ${d.summary}`);
  }
  return lines.join("\n");
}

function buildIdentityBlock(profile: DSProfile): string {
  const identity = {
    name: profile.name,
    version: profile.version,
    cdf_version: profile.cdf_version,
    dtcg_version: profile.dtcg_version,
    description: profile.description,
  };
  return stringify(identity, { lineWidth: 100, defaultStringType: "PLAIN" }).trimEnd();
}

function stringifySection(key: string, value: unknown): string {
  return stringify({ [key]: value }, {
    lineWidth: 100,
    defaultStringType: "PLAIN",
    blockQuote: "literal",
  });
}

// ─── Helpers ────────────────────────────────────────────────────────────────

function isEmpty(value: unknown): boolean {
  if (value === undefined || value === null) return true;
  if (Array.isArray(value)) return value.length === 0;
  if (typeof value === "object") return Object.keys(value as object).length === 0;
  return false;
}
